name: Build and Deploy LaTeX
on: [push]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex

      - name: Prepare Pages Content
        run: |
          mkdir pages
          mv index.html resume.pdf pages/

      - name: Upload Pages Content
        uses: actions/upload-pages-artifact@v3
        with:
          path: pages/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
